class ActionType:
    CLICK = "Click"
    PRESS = "Press"
    MOVE = "Move"
    RUN = "Run"
    MOVE_CAMERA = "Move camera"
    WAIT = "Wait"
    PROMO_CODES = "PromoCodes"
    TELEPORT_MONDSTADT_WINDWAIL = "Teleport Mondstadt Windwail statue"
    TELEPORT_MONDSTADT_WOLVENDOM = "Teleport Mondstadt Wolvendom waypoint"
    TELEPORT_MONDSTADT_WINDRISE = "Teleport Mondstadt Windrise statue"
    TELEPORT_MONDSTADT_STORM_TERROR_LAIR_LEFT = "Teleport Mondstadt Stormterror's Lair left waypoint"
    TELEPORT_LIYUE_HARBOR = "Teleport Liyue Harbor waypoint"
    TELEPORT_AVIDYA_FOREST_UP = "Teleport Avidya Forest upper waypoint"
